# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTokenModel',
            fields=[
                ('version', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('expirationTime', models.BigIntegerField(blank=True, null=True)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'db_table': 'active_tokens_MRSXMLLFNR3GS43QOJQW443LMV3GSY3IOVZQ____',
            },
        ),
        migrations.CreateModel(
            name='ArchivedTokenModel',
            fields=[
                ('version', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('expirationTime', models.BigIntegerField(blank=True, null=True)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'db_table': 'archived_tokens_MRSXMLLFNR3GS43QOJQW443LMV3GSY3IOVZQ____',
            },
        ),
        migrations.CreateModel(
            name='CachedDataModel',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cached_data_MRSXMLLFNR3GS43QOJQW443LMV3GSY3IOVZQ____',
            },
        ),
    ]
